name: wifi_connector
description: Flutter plug-in for connecting to wifi.
version: 1.0.2
homepage: https://wonjerry.github.io/
repository: https://github.com/wonjerry/flutter_wifi_connector

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.wonjerry.wifi_connector
    pluginClass: WifiConnectorPlugin